version: "1.0"

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
